
node() {
  stage('Checkout') {
    dir('checkout') {
      stage_checkout()
      stash name: 'checkout', includes: '**', useDefaultExcludes: false
    }
  }
  stage('Build') {
    dir('build') {
      unstash 'checkout'
      stage_build()
      stash name: 'build', includes: 'build/classes/**'
    }
  }
  
  parallel(
    'Test': {
      stage('Test') {
        dir('test') {
          unstash 'checkout'
          unstash 'build'
          stage_test()
        }
      }       
    },
    
    'Quality Check': {
      stage('Quality Check') {
        dir('quality-check') {
          unstash 'checkout'
          unstash 'build'
          stage_quality_check()
        }
      }        
    }
  ) 
}
